# Generated by Django 5.1.3 on 2024-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
